### ISSUE TITLE
Red screens when running your example

### ISSUE THREAD

**Issue by willvlad** [Eternali/custom_radio#1]

**Comment by Cedar7** [comment]
following is the error whenever a radio was clicked:

I/flutter ( 8187): #143    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 8187): #144    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 8187): #145    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 8187): #146    _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 8187): #147    _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 8187): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8187): Another exception was thrown: 'package:custom_radio/custom_radio.dart': error: line 102 pos 36: file:///C:/Users/n.mansour/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/custom_radio-0.1.2/lib/custom_radio.dart:102:36: Error: The argument type '(dart.core::Null) → dart.core::Null' can't be assigned to the parameter type '(void) → dynamic'.
I/flutter ( 8187): Another exception was thrown: A RenderFlex overflowed by 199711 pixels on the right.

**Comment by chunhunghan** [comment]
encounter the same issue. Thanks

**Comment by zebragg** [comment]
> 



> encounter the same issue.
> I just change line 102 to _controller.reverse();
> Thanks

like this   (97-108)  lines
```
 void _updateState() {
    setState(() {
      if (widget.checked && _controller.status != AnimationStatus.completed) {
        _controller.forward();
      } else {
        // _controller.reverse().then((Null value) {
        //   setState(() {});
        // });
        _controller.reverse();
      }
    });
  }

```

**Comment by rkmax** [comment]
would be nice to have this fixed in a new release
